style = "compact"

[stats]
# Set commands where we should consider the subcommand for statistics. Eg, kubectl get vs just kubectl
common_subcommands = [
    "uv",
    "just",
    "git",
    "tmux",
    "sudo",
]

# Set commands that should be totally stripped and ignored from stats
common_prefix = ["sudo"]

# Set commands that will be completely ignored from stats
ignored_commands = [
    "clear",
    "exit",
]

[dotfiles]
enabled = false
