#!/bin/zsh

# Time ZSH loadup, read more here: https://blog.mattclemente.com/2020/06/26/oh-my-zsh-slow-to-load.html#summary

shell=${1-$SHELL}
for i in $(seq 1 10); do /usr/bin/time $shell -i -c exit; done
