#!/bin/zsh

# Kill apps that match string, based on: https://github.com/sunknudsen/privacy-guides/tree/master/how-to-make-sure-app-is-not-running-in-the-background-on-macos

IFS=$'\n'
red=$(tput setaf 1)
normal=$(tput sgr0)

if [ -z "$1" ] || [ "$1" = "--help" ]; then
  printf "%s\n" "Usage: killapps [string]"
  return 0
fi

printf "%s\n" "Finding apps that match “$1”…"
sleep 1

processes=($(pgrep -afil "$1"))

if [ ${#processes[@]} -eq 0 ]; then
  printf "%s\n" "No apps found"
  return 0
else
  printf "%s\n" "${processes[@]}"
  printf "$red%s$normal" "Kill found apps (y or n)? "
  read -r answer
  if [ "$answer" = "y" ]; then
    printf "%s\n" "Killing found apps…"
    sleep 1
    for process in "${processes[@]}"; do
      echo $process | awk '{print $1}' | xargs sudo kill 2>&1 | grep -v "No such process"
    done
    printf "%s\n" "Done"
    return 0
  fi
fi
