theme = "base16_transparent"

[editor]
line-number = "relative"
scroll-lines = 1
auto-pairs = false
mouse = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
# Surface key remaps from Kitty
'C-a' = 'goto_line_start'
'C-e' = 'goto_line_end'
'A-b' = 'move_prev_word_start'
'A-f' = 'move_next_word_end'
'C-u' = 'goto_line_end'

[keys.insert]
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
