[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
# You can uncomment the following lines to open up terminal with alt + enter shortcut (like in i3)
# alt-enter = '''exec-and-forget osascript -e '
# tell application "Terminal"
#     do script
#     activate
# end tell'
# '''

# Other modes
cmd-alt-ctrl-space = 'mode apps'

cmd-alt-ctrl-f = 'fullscreen'
cmd-alt-ctrl-shift-f = 'fullscreen'
cmd-alt-ctrl-shift-r = 'flatten-workspace-tree'

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
cmd-alt-ctrl-l = 'layout floating tiling'
cmd-alt-ctrl-shift-t = 'layout tiles horizontal vertical'
cmd-alt-ctrl-shift-a = 'layout accordion horizontal vertical'
cmd-alt-ctrl-sectionSign = 'resize smart +150'
cmd-alt-ctrl-shift-sectionSign = 'resize smart -150'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
cmd-alt-ctrl-left = 'focus left'
cmd-alt-ctrl-down = 'focus down'
cmd-alt-ctrl-up = 'focus up'
cmd-alt-ctrl-right = 'focus right'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
cmd-alt-ctrl-shift-left = 'move left'
cmd-alt-ctrl-shift-down = 'move down'
cmd-alt-ctrl-shift-up = 'move up'
cmd-alt-ctrl-shift-right = 'move right'

cmd-alt-ctrl-shift-h = ['join-with left', 'layout accordion']
cmd-alt-ctrl-shift-j = ['join-with down', 'layout accordion']
cmd-alt-ctrl-shift-k = ['join-with up', 'layout accordion']
cmd-alt-ctrl-shift-l = ['join-with right', 'layout accordion']

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
cmd-alt-ctrl-1 = 'workspace 1'
cmd-alt-ctrl-2 = 'workspace 2'
cmd-alt-ctrl-3 = 'workspace 3'
cmd-alt-ctrl-q = 'workspace q'
cmd-alt-ctrl-w = 'workspace w'
cmd-alt-ctrl-e = 'workspace e'
cmd-alt-ctrl-s = 'workspace s'
cmd-alt-ctrl-p = 'workspace p'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
cmd-alt-ctrl-shift-1 = 'move-node-to-workspace 1 --focus-follows-window'
cmd-alt-ctrl-shift-2 = 'move-node-to-workspace 2 --focus-follows-window'
cmd-alt-ctrl-shift-3 = 'move-node-to-workspace 3 --focus-follows-window'
cmd-alt-ctrl-shift-q = 'move-node-to-workspace q --focus-follows-window'
cmd-alt-ctrl-shift-w = 'move-node-to-workspace w --focus-follows-window'
cmd-alt-ctrl-shift-e = 'move-node-to-workspace e --focus-follows-window'
cmd-alt-ctrl-shift-s = 'move-node-to-workspace s --focus-follows-window'
cmd-alt-ctrl-shift-p = 'move-node-to-workspace p --focus-follows-window'

cmd-alt-ctrl-tab = 'workspace-back-and-forth'
cmd-ctrl-tab = 'exec-and-forget aerospace list-workspaces --monitor focused --empty no | aerospace workspace next'
cmd-alt-ctrl-shift-tab = 'exec-and-forget aerospace list-workspaces --monitor focused --empty no | aerospace workspace prev'
# cmd-alt-ctrl-shift-tab = 'move-workspace-to-monitor --wrap-around next'

cmd-alt-ctrl-esc = '''exec-and-forget osascript -e 'tell application "System Events" to sleep' '''
