[workspace-to-monitor-force-assignment]
1 = 'main'
2 = 'main'
3 = 'main'
4 = 'main'
5 = 'main'
6 = 'main'
s = ['built-in', 'secondary']
p = 'main'

# [[on-window-detected]]
# if.app-id = 'com.apple.systempreferences'
# if.app-name-regex-substring = 'settings'
# if.window-title-regex-substring = 'substring'
# if.workspace = 'workspace-name'
# if.during-aerospace-startup = true
# check-further-callbacks = true
# run = ['layout floating', 'move-node-to-workspace S']  # The callback itself

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.Safari'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.iCal'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.QuickTimePlayerX'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.mail'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.Notes'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.1password.1password'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'notes'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.pioneerdj.rekordboxdj'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'camera'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'telegram'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'dicord'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'discord'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.microsoft.Outlook'
run = 'move-node-to-workspace e'

[[on-window-detected]]
if.app-id = 'com.microsoft.teams2'
run = 'move-node-to-workspace e'

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = 'move-node-to-workspace e'

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = 'move-node-to-workspace s'

[[on-window-detected]]
if.app-id = 'com.rambox'
run = 'move-node-to-workspace s'

[[on-window-detected]]
if.app-id = 'com.brave.Browser'
run = 'move-node-to-workspace p'
