.cache/zim/zimfw.zsh:
  type: file
  url: "https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh"
  refreshPeriod: 168h

{{- if (eq .chezmoi.os "darwin") }}
.hammerspoon:
  type: archive
  url: "https://github.com/jussapaavo/dot_hammerspoon/archive/refs/heads/main.zip"
  exact: true
  stripComponents: 1
  refreshPeriod: 168h

.hammerspoon/Spoons/Hyper.spoon:
  type: archive
  url: "https://github.com/evantravers/Hyper.spoon/archive/refs/heads/master.zip"
  exact: true
  stripComponents: 1
  refreshPeriod: 168h

.hammerspoon/Spoons/ReloadConfiguration.spoon:
  type: archive
  url: "https://github.com/Hammerspoon/Spoons/blob/master/Spoons/ReloadConfiguration.spoon.zip?raw=true"
  exact: true
  stripComponents: 1
  refreshPeriod: 168h
{{ end -}}

{{- if (eq .chezmoi.os "darwin") }}
agent-skills-anthropic:
  targetPath: ".config/opencode/skills"
  type: archive
  url: "https://github.com/anthropics/skills/archive/refs/heads/main.tar.gz"
  exact: true
  stripComponents: 2
  include:
    - "*/skills/skill-creator/**"
  refreshPeriod: 168h

agent-skills-astral:
  targetPath: ".config/opencode/skills"
  type: archive
  url: "https://github.com/astral-sh/claude-code-plugins/archive/refs/heads/main.tar.gz"
  exact: true
  stripComponents: 4
  include:
    - "*/plugins/astral/skills/uv/**"
  refreshPeriod: 168h

agent-skills-dbt:
  targetPath: ".config/opencode/skills"
  type: archive
  url: "https://github.com/dbt-labs/dbt-agent-skills/archive/refs/heads/main.tar.gz"
  exact: true
  stripComponents: 4
  include:
    - "*/skills/dbt/skills/**"
  refreshPeriod: 168h

agent-skills-obsidian:
  targetPath: ".config/opencode/skills"
  type: archive
  url: "https://github.com/kepano/obsidian-skills/archive/refs/heads/main.tar.gz"
  exact: true
  stripComponents: 2
  include:
    - "*/skills/**"
  exclude:
    - "*/.claude-plugin/**"
    - "*/skills/defuddle/**"
  refreshPeriod: 168h

agent-skills-terraform:
  targetPath: ".config/opencode/skills/terraform"
  type: archive
  url: "https://github.com/antonbabenko/terraform-skill/archive/refs/heads/master.tar.gz"
  exact: true
  stripComponents: 1
  include:
    - "*/references/**"
    - "*/SKILL.md"
  refreshPeriod: 168h
{{ end -}}
