[".oh-my-zsh"]
  type = "archive"
  url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
  type = "archive"
  url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
  type = "archive"
  url = "https://github.com/zsh-users/zsh-autosuggestions/archive/refs/heads/master.zip"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/git-open"]
  type = "archive"
  url = "https://github.com/paulirish/git-open/archive/refs/heads/master.zip"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

[".oh-my-zsh/custom/themes/powerlevel10k"]
  type = "archive"
  url = "https://github.com/romkatv/powerlevel10k/archive/v1.15.0.tar.gz"
  exact = true
  stripComponents = 1

{{- if (eq .chezmoi.os "darwin") }}
[".hammerspoon"]
  type = "archive"
  url = "https://github.com/jussapaavo/dot_hammerspoon/archive/refs/heads/main.zip"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

[".hammerspoon/Spoons/Hyper.spoon"]
  type = "archive"
  url = "https://github.com/evantravers/Hyper.spoon/archive/refs/heads/master.zip"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

[".hammerspoon/Spoons/MicMute.spoon"]
  type = "archive"
  url = "https://github.com/Hammerspoon/Spoons/blob/master/Spoons/MicMute.spoon.zip?raw=true"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

[".hammerspoon/Spoons/ReloadConfiguration.spoon"]
  type = "archive"
  url = "https://github.com/Hammerspoon/Spoons/blob/master/Spoons/ReloadConfiguration.spoon.zip?raw=true"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
{{ end -}}
