.cache/zim/zimfw.zsh:
  type: file
  url: "https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh"
  refreshPeriod: 168h

{{- if (eq .chezmoi.os "darwin") }}
.hammerspoon:
  type: archive
  url: "https://github.com/jussapaavo/dot_hammerspoon/archive/refs/heads/main.zip"
  exact: true
  stripComponents: 1
  refreshPeriod: 168h

.hammerspoon/Spoons/Hyper.spoon:
  type: archive
  url: "https://github.com/evantravers/Hyper.spoon/archive/refs/heads/master.zip"
  exact: true
  stripComponents: 1
  refreshPeriod: 168h

.hammerspoon/Spoons/ReloadConfiguration.spoon:
  type: archive
  url: "https://github.com/Hammerspoon/Spoons/blob/master/Spoons/ReloadConfiguration.spoon.zip?raw=true"
  exact: true
  stripComponents: 1
  refreshPeriod: 168h
{{ end -}}

{{- if and (eq .chezmoi.os "linux") }}
{{- $fontDir := ".local/share/fonts" }}
{{ $fontDir }}/MesloLGS NF Regular.ttf:
  type: file
  url: "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS NF"
    Regular.ttf
  refreshPeriod: 168h

{{ $fontDir }}/MesloLGS NF Bold.ttf:
  type: file
  url: "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS NF"
    Bold.ttf
  refreshPeriod: 168h

{{ $fontDir }}/MesloLGS NF Italic.ttf:
  type: file
  url: "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS NF"
    Italic.ttf
  refreshPeriod: 168h

{{ $fontDir }}/MesloLGS NF Bold Italic.ttf:
  type: file
  url: "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS NF Bold Italic.ttf"
  refreshPeriod: 168h
{{- end }}
